name: Publish to PyPI

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-sdist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Install build tools
        run: pip install build

      - name: Build package
        run: python -m build --sdist

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: pkg-sdist
          path: ./dist/*.tar.gz

  publish:
    needs: [build-sdist]
    runs-on: ubuntu-latest

    environment:
      name: release
      url: https://pypi.org/project/sqlalchemy-fake-model

    permissions:
      id-token: write

    steps:
      - name: Download built packages
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
